from pathlib import Path

from tools.filesystem import write_file


def scaffold_saas(project_dir: str, app_name: str) -> str:
    base = Path(project_dir).resolve()
    package_json = """{
  "name": "nexus-saas",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "15.3.1",
    "react": "19.1.0",
    "react-dom": "19.1.0"
  }
}
"""
    layout = f"""export default function RootLayout({{ children }}) {{
  return (
    <html lang="en">
      <body style={{{{fontFamily: "Segoe UI, sans-serif", margin: 0, background: "#f5f1e8", color: "#1f1c17"}}}}>
        {{children}}
      </body>
    </html>
  );
}}
"""
    page = f"""export default function Home() {{
  return (
    <main style={{{{padding: "64px", maxWidth: 960, margin: "0 auto"}}}}>
      <h1>{app_name}</h1>
      <p>Landing page, auth path, and dashboard scaffold generated by NEXUS.</p>
      <section style={{{{display: "grid", gap: 16, gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))"}}}}>
        <div style={{{{padding: 24, background: "#fff", borderRadius: 16}}}}>Auth</div>
        <div style={{{{padding: 24, background: "#fff", borderRadius: 16}}}}>Dashboard</div>
        <div style={{{{padding: 24, background: "#fff", borderRadius: 16}}}}>Billing</div>
      </section>
    </main>
  );
}}
"""
    write_file(str(base / "package.json"), package_json)
    write_file(str(base / "app" / "layout.js"), layout)
    write_file(str(base / "app" / "page.js"), page)
    return f"Scaffolded SaaS app in {base}"

